version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - run:
          name: Install packages including xvfb
          command: |
            apt-get update && apt-get install default-jdk -y && apt-get install unzip xvfb libxi6 libgconf-2-4 -y

      - run:
          name: Create JMeter directory and download JMeter
          command: |
            mkdir /opt/jmeter && cd /opt/jmeter && apt-get install wget -y
            wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.zip && unzip apache-jmeter-5.6.2.zip

      - run:
          name: Install Webdriver plugin
          command: |
            cd /opt/jmeter/apache-jmeter-5.6.2 && wget https://jmeter-plugins.org/files/packages/jpgc-webdriver-3.2.zip && unzip jpgc-webdriver-3.2.zip

      - run:
          name: Install geckodriver
          command: |
            cd /opt/jmeter && mkdir bin && cd bin && wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz && tar -xzf geckodriver-v0.27.0-linux32.tar.gz

      - run:
          name: Install Firefox
          command: |
            apt-get install firefox -y

      - run:
          name: Add JMeter and geckodriver folders to PATH
          command: |
            echo 'PATH="/apache-jmeter-5.3/bin:/opt/jmeter/bin:${PATH}"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Set xvfb Screen Number
          command: |
            echo 'DISPLAY=:99' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Change geckodriver permissions
          command: |
            chmod +x /opt/jmeter/bin/geckodriver
            chown root:root /opt/jmeter/bin/geckodriver

      - run:
          name: Install Docker
          command: |
            wget -O get-docker.sh https://get.docker.com
            sh get-docker.sh
            sudo usermod -aG docker root

      - run:
          name: Build Docker image
          command: docker build -t jmeter-webdriver:0.5 .

      - run:
          name: List Docker images
          command: docker images


      - run:
          name: Run docker container
          command: docker run -it \
                   -v $(pwd)/results:/opt/jmeter/results \
                   -v $(pwd)/jmx:/opt/jmeter/jmx \
                   jmeter-webdriver:0.5 bash     
      - run:
          name: Run test 
          command: Xvfb :99 & ; cd /opt/jmeter ; jmeter -n -t jmx/jmeter-webdriver.jmx -l results/scriptresults.jtl -e -o results/jmeter-reports

